@host = http://localhost:5098/api

### POST Create order
POST {{host}}/orders/
Accept: text/plain
Content-Type: application/json

{
  "userEmail": "user1@eshop.com",
  "shippingAddress": "Polna 1, 33-333 Kraków",
  "positions": [
    {
      "productId": 1,
      "amount": 1
    },
    {
      "productId": 2,
      "amount": 2
    }
  ]
}

> {%
    client.test("Create order", () => {
        client.assert(response.body > 0)
    });
    client.global.set("orderId", response.body);
%}

### GET order
GET {{host}}/orders/{{orderId}}
Accept: application/json

> {%
    client.test("Return order", () => {
        const body = response.body;
        client.assert(body.id == client.global.get("orderId"));
        client.assert(body.status === "Created");
        client.assert(body.shippingAddress == "Polna 1, 33-333 Kraków");
        client.assert(body.positions.length == 2);
        client.assert(body.positions[0].productId == 1);
        client.assert(body.positions[0].amount == 1);
        client.assert(body.positions[1].productId == 2);
        client.assert(body.positions[1].amount == 2);
    })
%}

### PUT add order position
PUT {{host}}/orders/addPosition
Accept: text/plain
Content-Type: application/json

{
  "orderId": {{orderId}},
  "productId": 3,
  "amount": 1
}

> {%
    client.test("Add order position", () => {
        client.assert(response.status === 200);
    })
%}


### PUT remove order position
PUT {{host}}/orders/removePosition
Accept: text/plain
Content-Type: application/json

{
  "orderId": {{orderId}},
  "productId": 3
}

> {%
    client.test("Remove order position", () => {
        client.assert(response.status === 200);
    })
%}

### POST pay the order
POST {{host}}/orders/pay
Accept: text/plain
Content-Type: application/json

{
  "orderId": {{orderId}}
}

> {%
    client.test("Pay the order", () => {
        client.assert(response.status === 200);
    })
%}

### POST ship the order
POST {{host}}/orders/ship
Accept: text/plain
Content-Type: application/json

{
  "orderId": {{orderId}}
}

> {%
    client.test("Ship the order", () => {
        client.assert(response.status === 200);
    })
%}

### GET all orders
GET {{host}}/orders
Accept: application/json

> {%
    client.test("Get all orders", () => {
        client.assert(response.status === 200);
    })
%}

### GET order history
GET {{host}}/orders/{{orderId}}/history
Accept: application/json

> {%
    client.test("Get order history", () => {
        client.assert(response.status === 200);
    })
%}
