<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lightstreamer.DotNetStandard.Adapters" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
</Project>
