version: "3"
include:
    - infrastructure/docker-compose.yml

services:
    eshop-api:
        container_name: "eshop-api"
        image: "eshop-api-image:latest"
        restart: on-failure
        ports:
            - "5050:5050"
            - "5051:5051"
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_Kestrel__Certificates__Default__Password=mdorwonthappen
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.net/https/eshop.pfx
            - ASPNETCORE_URLS=https://+:5051;http://+:5050
            - USE_KESTREL_DEV_HTTPS=true
        volumes:
            - ./infrastructure/:/root/.net/https/
        networks:
            - eshop-default

networks:
    eshop-default:
        external:
            name: eshop_network
