<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Convey.CQRS.Commands" />
      <PackageReference Include="Convey.CQRS.Events" />
      <PackageReference Include="Convey.CQRS.Queries" />
      <PackageReference Include="Convey.MessageBrokers" />
      <PackageReference Include="Convey.MessageBrokers.CQRS" />
      <PackageReference Include="Convey.MessageBrokers.RabbitMQ" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    </ItemGroup>

</Project>
