<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>false</InvariantGlobalization>
        <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
        <RootNamespace>eShop</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Boxed.AspNetCore.Swagger" />
        <PackageReference Include="Convey.CQRS.Commands" />
        <PackageReference Include="Convey.CQRS.Queries" />
        <PackageReference Include="Convey.MessageBrokers.CQRS" />
        <PackageReference Include="Convey.MessageBrokers.RabbitMQ" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\eShop.Application\eShop.Application.csproj" />
      <ProjectReference Include="..\eShop.Infrastructure\eShop.Infrastructure.csproj" />
    </ItemGroup>

</Project>
